<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
    	DB::beginTransaction();
    	DB::table('user_group')->truncate();
        DB::table('user_group')->updateOrInsert(
                ['slug' => 'satker'],
                [
					'id'     	=> 1,
					'name'    	=> 'satker',
					'ref_table' => 'ref_satker',
					'kolom'   	=> 'kdsatker',
					'nama'   	=> 'nmsatker'
				]
            );


        DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300617'], ['nmsatker'  => 'DINAS SOSIAL, TENAGA KERJA DAN TRANSMIGRASI KAB. BELITUNG TIMUR', 'kddept'     => '026', 'kdbaes1' => '02601', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300134'], ['nmsatker'  => 'DINAS TENAGA KERJA DAN SOSIAL KAB. BELITUNG', 'kddept'     => '026', 'kdbaes1' => '02601', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309047'], ['nmsatker'  => 'DINAS SOSIAL, TENAGA KERJA DAN TRANSMIGRASI KAB. BELITUNG TIMUR', 'kddept'     => '026', 'kdbaes1' => '02607', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309225'], ['nmsatker'  => 'DINAS SOSIAL, TENAGA KERJA DAN TRANSMIGRASI KAB. BELITUNG', 'kddept'     => '026', 'kdbaes1' => '02604', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '418573'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02509', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '664038'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG TIMUR', 'kddept'     => '025', 'kdbaes1' => '02509', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '418572'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02508', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '424973'], ['nmsatker'  => 'MADRASAH TSANAWIYAH NEGERI 1 BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '590566'], ['nmsatker'  => 'MADRASAH IBTIDAIYAH NEGERI 1 BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '675912'], ['nmsatker'  => 'MADRASAH IBTIDAIYAH NEGERI 2 BELITUNG KAB. BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '575947'], ['nmsatker'  => 'MADRASAH ALIYAH NEGERI 1 BELITUNG KAB. BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '574387'], ['nmsatker'  => 'MADRASAH TSANAWIYAH NEGERI 1 BELITUNG TIMUR KAB. BELITUNG TIMUR', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '664037'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG TIMUR', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '418571'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '418570'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02503', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '664036'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG TIMUR', 'kddept'     => '025', 'kdbaes1' => '02503', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '418569'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG', 'kddept'     => '025', 'kdbaes1' => '02501', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '664035'], ['nmsatker'  => 'KANTOR KEMENTERIAN AGAMA KAB. BELITUNG TIMUR', 'kddept'     => '025', 'kdbaes1' => '02501', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '445892'], ['nmsatker'  => 'PELABUHAN PERIKANAN NUSANTARA TANJUNG PANDAN', 'kddept'     => '032', 'kdbaes1' => '03205', 'kdkppn'    => '107', 'kdkewenangan'    => 'KP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '400624'], ['nmsatker'  => 'DINAS KEBUDAYAAN DAN PARIWISATA KAB. BELITUNG', 'kddept'     => '040', 'kdbaes1' => '04001', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300145'], ['nmsatker'  => 'DINAS KOPERASI DAN UKM KAB. BELITUNG', 'kddept'     => '044', 'kdbaes1' => '04401', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '400625'], ['nmsatker'  => 'DINAS PARIWISATA DAN EKONOMI KREATIF KABUPATEN BELITUNG', 'kddept'     => '040', 'kdbaes1' => '04001', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '502459'], ['nmsatker'  => 'PEMBANGUNAN INFRASTRUKTUR PERMUKIMAN KAB. BELITUNG TIMUR', 'kddept'     => '033', 'kdbaes1' => '03305', 'kdkppn'    => '107', 'kdkewenangan'    => 'DS', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '502413'], ['nmsatker'  => 'PEMBANGUNAN INFRASTRUKTUR PERMUKIMAN KAB. BELITUNG', 'kddept'     => '033', 'kdbaes1' => '03305', 'kdkppn'    => '107', 'kdkewenangan'    => 'DS', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300610'], ['nmsatker'  => 'DINAS KELAUTAN DAN PERIKANAN KAB. BELITUNG TIMUR', 'kddept'     => '032', 'kdbaes1' => '03201', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '400668'], ['nmsatker'  => 'Dinas Kelautan dan Perikanan Kab. Belitung', 'kddept'     => '032', 'kdbaes1' => '03203', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300139'], ['nmsatker'  => 'DINAS KELAUTAN DAN PERIKANAN KABUPATEN BELITUNG', 'kddept'     => '032', 'kdbaes1' => '03201', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '237792'], ['nmsatker'  => 'STASIUN KARANTINA TUMBUHAN KELAS II TANJUNG PANDAN', 'kddept'     => '018', 'kdbaes1' => '01812', 'kdkppn'    => '107', 'kdkewenangan'    => 'KP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300149'], ['nmsatker'  => 'DINAS TANAMAN PANGAN DAN HORTIKULTURA, PETERNAKAN, PERKEBUNAN, KEHUTANAN DAN KETAHANAN PANGAN KABUPATEN BELITUNG', 'kddept'     => '018', 'kdbaes1' => '01804', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309244'], ['nmsatker'  => 'DINAS PERTANIAN DAN KEHUTANAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '018', 'kdbaes1' => '01803', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300604'], ['nmsatker'  => 'DINAS PERTANIAN DAN KEHUTANAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '018', 'kdbaes1' => '01801', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300140'], ['nmsatker'  => 'DINAS PERKEBUNAN KABUPATEN BELITUNG', 'kddept'     => '018', 'kdbaes1' => '01801', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300128'], ['nmsatker'  => 'DINAS PERTANIAN KABUPATEN BELITUNG', 'kddept'     => '018', 'kdbaes1' => '01801', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300136'], ['nmsatker'  => 'DINAS PETERNAKAN KABUPATEN BELITUNG', 'kddept'     => '018', 'kdbaes1' => '01801', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300119'], ['nmsatker'  => 'DINAS PERTANIAN DAN KEHUTANAN KABUPATEN BELITUNG', 'kddept'     => '018', 'kdbaes1' => '01801', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309245'], ['nmsatker'  => 'DINAS PERTANIAN DAN KEHUTANAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '018', 'kdbaes1' => '01808', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309224'], ['nmsatker'  => 'DINAS PERTANIAN DAN KEHUTANAN KABUPATEN BELITUNG', 'kddept'     => '018', 'kdbaes1' => '01808', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '502460'], ['nmsatker'  => 'DINKES. KAB. BELITUNG TIMUR', 'kddept'     => '024', 'kdbaes1' => '02404', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300637'], ['nmsatker'  => 'DINKES KAB. BELITUNG TIMUR', 'kddept'     => '024', 'kdbaes1' => '02404', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300123'], ['nmsatker'  => 'RSU TANJUNG PANDAN/ RSU BELITUNG', 'kddept'     => '024', 'kdbaes1' => '02404', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '402140'], ['nmsatker'  => 'RSUD DR. H. MARSIDI JUDONO', 'kddept'     => '024', 'kdbaes1' => '02404', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309223'], ['nmsatker'  => 'DINAS KESEHATAN KAB. BELITUNG', 'kddept'     => '024', 'kdbaes1' => '02404', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300627'], ['nmsatker'  => 'DINAS KESEHATAN KAB. BELITUNG TIMUR', 'kddept'     => '024', 'kdbaes1' => '02401', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300116'], ['nmsatker'  => 'DINAS KESEHATAN KAB. BELITUNG', 'kddept'     => '024', 'kdbaes1' => '02401', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309221'], ['nmsatker'  => 'DINAS KESEHATAN KAB. BELITUNG', 'kddept'     => '024', 'kdbaes1' => '02403', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309246'], ['nmsatker'  => 'DINAS KESEHATAN KAB. BELITUNG TIMUR', 'kddept'     => '024', 'kdbaes1' => '02403', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '288312'], ['nmsatker'  => 'BANDAR UDARA A.S HANANDJOEDDIN DI TANJUNG PANDAN', 'kddept'     => '022', 'kdbaes1' => '02205', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '413287'], ['nmsatker'  => 'KANTOR KESYAHBANDARAN DAN OTORITAS PELABUHAN TANJUNG PANDAN', 'kddept'     => '022', 'kdbaes1' => '02204', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '413381'], ['nmsatker'  => 'UNIT PENYELENGGARA PELABUHAN MANGGAR', 'kddept'     => '022', 'kdbaes1' => '02204', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '007261'], ['nmsatker'  => 'KEJAKSAAN NEGERI BELITUNG', 'kddept'     => '006', 'kdbaes1' => '00601', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '009755'], ['nmsatker'  => 'KEJAKSAAN NEGERI BELITUNG TIMUR', 'kddept'     => '006', 'kdbaes1' => '00601', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '402319'], ['nmsatker'  => 'PENGADILAN AGAMA TANJUNG PANDAN', 'kddept'     => '005', 'kdbaes1' => '00504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '402318'], ['nmsatker'  => 'PENGADILAN AGAMA TANJUNG PANDAN', 'kddept'     => '005', 'kdbaes1' => '00501', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '400600'], ['nmsatker'  => 'PENGADILAN NEGERI TANJUNG PANDAN', 'kddept'     => '005', 'kdbaes1' => '00501', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300629'], ['nmsatker'  => 'SEKRETARIAT DAERAH KAB. BELITUNG TIMUR', 'kddept'     => '010', 'kdbaes1' => '01001', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300143'], ['nmsatker'  => 'SEKRETARIAT DAERAH KAB. BELITUNG', 'kddept'     => '010', 'kdbaes1' => '01001', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309247'], ['nmsatker'  => 'KANTOR PEMBERDAYAAN MASYARAKAT DAN PEMERINTAHAN DESA KAB. BELITUNG TIMUR', 'kddept'     => '010', 'kdbaes1' => '01005', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300636'], ['nmsatker'  => 'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL KABUPATEN BELITUNG TIMUR', 'kddept'     => '010', 'kdbaes1' => '01008', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300150'], ['nmsatker'  => 'DINAS KEPENDUDUKAN & PENCATATAN SIPIL KABUPATEN BELITUNG', 'kddept'     => '010', 'kdbaes1' => '01008', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '406513'], ['nmsatker'  => 'LEMBAGA PEMASYARAKATAN TANJUNG PANDAN', 'kddept'     => '013', 'kdbaes1' => '01301', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '527982'], ['nmsatker'  => 'KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG PANDAN', 'kddept'     => '015', 'kdbaes1' => '01508', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '411152'], ['nmsatker'  => 'KANTOR PENGAWASAN DAN PELAYANAN BC TANJUNG PANDAN', 'kddept'     => '015', 'kdbaes1' => '01505', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '673411'], ['nmsatker'  => 'KANTOR PELAYANAN PENYULUHAN DAN KONSULTASI PERPAJAKAN MANGGAR', 'kddept'     => '015', 'kdbaes1' => '01504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '410580'], ['nmsatker'  => 'KANTOR PELAYANAN PAJAK PRATAMA TANJUNG PANDAN', 'kddept'     => '015', 'kdbaes1' => '01504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '109160'], ['nmsatker'  => 'KANTOR IMIGRASI KELAS II TANJUNG PANDAN', 'kddept'     => '013', 'kdbaes1' => '01306', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '344831'], ['nmsatker'  => 'LANUD H. ABDULLAH SANUSI HANANDJOEDDIN', 'kddept'     => '012', 'kdbaes1' => '01224', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '406514'], ['nmsatker'  => 'LEMBAGA PEMASYARAKATAN TANJUNG PANDAN', 'kddept'     => '013', 'kdbaes1' => '01305', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '419000'], ['nmsatker'  => 'DINAS KOPERASI, PERINDUSTRIAN DAN PERDAGANGAN KABUPATEN BELITUNG', 'kddept'     => '044', 'kdbaes1' => '04401', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300146'], ['nmsatker'  => 'DINAS KEBUDAYAAN DAN PARIWISATA KAB. BELITUNG', 'kddept'     => '040', 'kdbaes1' => '04005', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '498594'], ['nmsatker'  => 'PELAKSANAAN JALAN NASIONAL WILAYAH II PROVINSI BABEL', 'kddept'     => '033', 'kdbaes1' => '03304', 'kdkppn'    => '107', 'kdkewenangan'    => 'KP', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '502411'], ['nmsatker'  => 'PEMBANGUNAN INFRASTRUKTUR PERMUKIMAN KAB. BELITUNG', 'kddept'     => '033', 'kdbaes1' => '03305', 'kdkppn'    => '107', 'kdkewenangan'    => 'KP', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '502458'], ['nmsatker'  => 'PEMBANGUNAN INFRASTRUKTUR PERMUKIMAN KAB. BELITUNG TIMUR', 'kddept'     => '033', 'kdbaes1' => '03305', 'kdkppn'    => '107', 'kdkewenangan'    => 'KP', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300635'], ['nmsatker'  => 'DINAS KELAUTAN DAN PERIKANAN KAB. BELITUNG TIMUR', 'kddept'     => '032', 'kdbaes1' => '03206', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309226'], ['nmsatker'  => 'DINAS KELAUTAN DAN PERIKANAN KABUPATEN BELITUNG', 'kddept'     => '032', 'kdbaes1' => '03206', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '239221'], ['nmsatker'  => 'PELABUHAN PERIKANAN NUSANTARA TANJUNG PANDAN', 'kddept'     => '032', 'kdbaes1' => '03203', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300632'], ['nmsatker'  => 'DINAS PERINDUSTRIAN, PERDAGANGAN DAN KOPERASI KABUPATEN BELITUNG TIMUR', 'kddept'     => '090', 'kdbaes1' => '09001', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300144'], ['nmsatker'  => 'BAPPEDA DAN PM KAB. BELITUNG', 'kddept'     => '067', 'kdbaes1' => '06701', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300630'], ['nmsatker'  => 'DINAS PERTANIAN DAN KEHUTANAN KAB. BELITUNG TIMUR', 'kddept'     => '067', 'kdbaes1' => '06701', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403127'], ['nmsatker'  => 'KANTOR PERTANAHAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '056', 'kdbaes1' => '05609', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403088'], ['nmsatker'  => 'KANTOR PERTANAHAN KAB. BELITUNG', 'kddept'     => '056', 'kdbaes1' => '05609', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403126'], ['nmsatker'  => 'KANTOR PERTANAHAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '056', 'kdbaes1' => '05608', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403086'], ['nmsatker'  => 'KANTOR PERTANAHAN KAB. BELITUNG', 'kddept'     => '056', 'kdbaes1' => '05607', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403087'], ['nmsatker'  => 'KANTOR PERTANAHAN KAB. BELITUNG', 'kddept'     => '056', 'kdbaes1' => '05608', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403124'], ['nmsatker'  => 'KANTOR PERTANAHAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '056', 'kdbaes1' => '05606', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403125'], ['nmsatker'  => 'KANTOR PERTANAHAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '056', 'kdbaes1' => '05607', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403123'], ['nmsatker'  => 'KANTOR PERTANAHAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '056', 'kdbaes1' => '05605', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403082'], ['nmsatker'  => 'KANTOR PERTANAHAN KAB. BELITUNG', 'kddept'     => '056', 'kdbaes1' => '05605', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403085'], ['nmsatker'  => 'KANTOR PERTANAHAN KAB. BELITUNG', 'kddept'     => '056', 'kdbaes1' => '05606', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403122'], ['nmsatker'  => 'KANTOR PERTANAHAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '056', 'kdbaes1' => '05604', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403081'], ['nmsatker'  => 'KANTOR PERTANAHAN KAB. BELITUNG', 'kddept'     => '056', 'kdbaes1' => '05604', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '999057'], ['nmsatker'  => 'KPPN TANJUNG PANDAN (KUASA BUN)', 'kddept'     => '999', 'kdbaes1' => '99900', 'kdkppn'    => '107', 'kdkewenangan'    => 'DS', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300633'], ['nmsatker'  => 'DINAS PENANAMAN MODAL PELAYANAN TERPADU SATU PINTU DAN PERDAGANGAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '090', 'kdbaes1' => '09002', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '437121'], ['nmsatker'  => 'STASIUN METEOROLOGI H. ASAN HANANJOEDIN - BELITUNG', 'kddept'     => '075', 'kdbaes1' => '07501', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '656816'], ['nmsatker'  => 'KPU KABUPATEN BELITUNG', 'kddept'     => '076', 'kdbaes1' => '07601', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '437916'], ['nmsatker'  => 'STASIUN GEOFISIKA TANJUNG PANDAN', 'kddept'     => '075', 'kdbaes1' => '07501', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '656820'], ['nmsatker'  => 'KPU KABUPATEN BELITUNG TIMUR', 'kddept'     => '076', 'kdbaes1' => '07601', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '689540'], ['nmsatker'  => 'BADAN NARKOTIKA NASIONAL KABUPATEN BELITUNG', 'kddept'     => '066', 'kdbaes1' => '06601', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '665353'], ['nmsatker'  => 'POLRES BELITUNG TIMUR', 'kddept'     => '060', 'kdbaes1' => '06001', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '641410'], ['nmsatker'  => 'POLRES BELITUNG', 'kddept'     => '060', 'kdbaes1' => '06001', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '431195'], ['nmsatker'  => 'KANTOR PERTANAHAN KAB. BELITUNG', 'kddept'     => '056', 'kdbaes1' => '05601', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '675631'], ['nmsatker'  => 'KANTOR PERTANAHAN KABUPATEN BELITUNG TIMUR', 'kddept'     => '056', 'kdbaes1' => '05601', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '667261'], ['nmsatker'  => 'BADAN PUSAT STATISTIK KAB. BELITUNG TIMUR', 'kddept'     => '054', 'kdbaes1' => '05401', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '428315'], ['nmsatker'  => 'BADAN PUSAT STATISTIK KAB. BELITUNG', 'kddept'     => '054', 'kdbaes1' => '05401', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300608'], ['nmsatker'  => 'RSU BELITUNG TIMUR', 'kddept'     => '024', 'kdbaes1' => '02401', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300621'], ['nmsatker'  => 'DINAS PERTANIAN, PETERNAKAN DAN KETAHANAN PANGAN KAB. BANGKA TENGAH', 'kddept'     => '018', 'kdbaes1' => '01801', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300147'], ['nmsatker'  => 'DINAS PENDIDIKAN DAN KEBUDAYAAN KABUPATEN BELITUNG', 'kddept'     => '023', 'kdbaes1' => '02315', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300634'], ['nmsatker'  => 'DINAS KESEHATAN KAB. BELITUNG TIMUR', 'kddept'     => '024', 'kdbaes1' => '02405', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '400601'], ['nmsatker'  => 'PENGADILAN NEGERI TANJUNG PANDAN', 'kddept'     => '005', 'kdbaes1' => '00503', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300631'], ['nmsatker'  => 'KANTOR PEMBERDAYAAN MASYARAKAT DAN PEMERINTAHAN DESA KAB. BELITUNG TIMUR', 'kddept'     => '010', 'kdbaes1' => '01001', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '637965'], ['nmsatker'  => 'LANUD TANJUNG PANDAN', 'kddept'     => '012', 'kdbaes1' => '01224', 'kdkppn'    => '107', 'kdkewenangan'    => 'KP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '108203'], ['nmsatker'  => 'KANTOR IMIGRASI TANJUNG PANDAN', 'kddept'     => '013', 'kdbaes1' => '01301', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '309152'], ['nmsatker'  => 'DINAS TENAGA KERJA, KOPERASI, USAHA KECIL DAN MENENGAH KABUPATEN BELITUNG TIMUR', 'kddept'     => '026', 'kdbaes1' => '02604', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '673889'], ['nmsatker'  => 'MADRASAH IBTIDAIYAH NEGERI 1 BELITUNG TIMUR', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '400669'], ['nmsatker'  => 'Dinas Kelautan dan Perikanan Kab. Belitung Timur', 'kddept'     => '032', 'kdbaes1' => '03203', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '403691'], ['nmsatker'  => 'KPPN TANJUNG PANDAN PENGELOLA PENYALURAN DANA ALOKASI KHUSUS FISIK DAN DANA DESA', 'kddept'     => '999', 'kdbaes1' => '99905', 'kdkppn'    => '107', 'kdkewenangan'    => 'DS', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '300148'], ['nmsatker'  => 'DINAS PERINDUSTRIAN, PERDAGANGAN, KOPERASI DAN PENANAMAN MODAL KAB. BELITUNG', 'kddept'     => '090', 'kdbaes1' => '09002', 'kdkppn'    => '107', 'kdkewenangan'    => 'TP', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '108203'], ['nmsatker'  => 'KANTOR IMIGRASI TANJUNG PANDAN', 'kddept'     => '013', 'kdbaes1' => '01301', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '0'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '574387'], ['nmsatker'  => 'MADRASAH TSANAWIYAH NEGERI 1 BELITUNG TIMUR KAB. BELITUNG TIMUR', 'kddept'     => '025', 'kdbaes1' => '02504', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );
		DB::table('ref_satker')->updateOrInsert(['kdsatker' => '352631'], ['nmsatker'  => 'BALAI LATIHAN KERJA (BLK)BELITUNG', 'kddept'     => '026', 'kdbaes1' => '02613', 'kdkppn'    => '107', 'kdkewenangan'    => 'KD', 'status'    => '1'] );

        DB::commit();
    }
}
